/*
 * This file is generated by jOOQ.
 */
package com.jooq.db.tables.records


import com.jooq.db.tables.Book

import org.jooq.Field
import org.jooq.Record1
import org.jooq.Record3
import org.jooq.Row3
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class BookRecord() : UpdatableRecordImpl<BookRecord>(Book.BOOK), Record3<Int?, String?, String?> {

    var id: Int?
        set(value) = set(0, value)
        get() = get(0) as Int?

    var title: String?
        set(value) = set(1, value)
        get() = get(1) as String?

    var author: String?
        set(value) = set(2, value)
        get() = get(2) as String?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Int?> = super.key() as Record1<Int?>

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    override fun fieldsRow(): Row3<Int?, String?, String?> = super.fieldsRow() as Row3<Int?, String?, String?>
    override fun valuesRow(): Row3<Int?, String?, String?> = super.valuesRow() as Row3<Int?, String?, String?>
    override fun field1(): Field<Int?> = Book.BOOK.ID
    override fun field2(): Field<String?> = Book.BOOK.TITLE
    override fun field3(): Field<String?> = Book.BOOK.AUTHOR
    override fun component1(): Int? = id
    override fun component2(): String? = title
    override fun component3(): String? = author
    override fun value1(): Int? = id
    override fun value2(): String? = title
    override fun value3(): String? = author

    override fun value1(value: Int?): BookRecord {
        this.id = value
        return this
    }

    override fun value2(value: String?): BookRecord {
        this.title = value
        return this
    }

    override fun value3(value: String?): BookRecord {
        this.author = value
        return this
    }

    override fun values(value1: Int?, value2: String?, value3: String?): BookRecord {
        this.value1(value1)
        this.value2(value2)
        this.value3(value3)
        return this
    }

    /**
     * Create a detached, initialised BookRecord
     */
    constructor(id: Int? = null, title: String? = null, author: String? = null): this() {
        this.id = id
        this.title = title
        this.author = author
    }
}
