/*
 * This file is generated by jOOQ.
 */
package com.jooq.db


import com.jooq.db.tables.Book

import kotlin.collections.List

import org.jooq.Catalog
import org.jooq.Table
import org.jooq.impl.SchemaImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class Public : SchemaImpl("PUBLIC", DefaultCatalog.DEFAULT_CATALOG) {
    companion object {

        /**
         * The reference instance of <code>PUBLIC</code>
         */
        val PUBLIC = Public()
    }

    /**
     * The table <code>PUBLIC.BOOK</code>.
     */
    val BOOK get() = Book.BOOK

    override fun getCatalog(): Catalog = DefaultCatalog.DEFAULT_CATALOG

    override fun getTables(): List<Table<*>> = listOf(
        Book.BOOK
    )
}
